version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./docker-files/images:/home/user/images
    ports:
      - "2222:22"
    command: user:password:1001

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    volumes:
      - ./docker-files/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  grafana:
    build: "./docker-files/grafana"
    container_name: 'grafana'
    ports:
      - "13000:3000"