spring:
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 512MB

app:
  react:
    urls:
      - /login
      - /home
  jwt:
    secret: '024d1700-85de-45d8-9c4d-37ce2a545290'
    expiration: 60
  file:
    directory: ./images/
    host: localhost
    port: 2222
    username: user
    password: password
    extension-list:
      - jpg
      - jpeg
      - png
      - bmp