DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(80) NOT NULL,
  active BOOLEAN DEFAULT FALSE
);


DROP TABLE IF EXISTS photo;

CREATE TABLE photo (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  description VARCHAR(500) NULL,
  size INT NOT NULL,
  uploaded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);


DROP TABLE IF EXISTS hashtag;

CREATE TABLE hashtag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS hashtag_photo;

CREATE TABLE hashtag_photo (
  photo_id BIGINT,
  hashtag_id BIGINT,
  PRIMARY KEY (photo_id, hashtag_id),
  FOREIGN KEY (photo_id) REFERENCES photo(id),
  FOREIGN KEY (hashtag_id) REFERENCES hashtag(id)
);