DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role ENUM('ROLE_ADMIN', 'ROLE_USER') NOT NULL,
  password VARCHAR(80) NOT NULL,
  active BOOLEAN DEFAULT FALSE,
  registered DATE DEFAULT CURRENT_DATE,
  avatar VARCHAR(40) DEFAULT 'user.png',
  plan ENUM('ARTIST', 'BUYER') NOT NULL
);


DROP TABLE IF EXISTS photo;

CREATE TABLE photo (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(500) NULL,
  size INT NOT NULL,
  uploaded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);


DROP TABLE IF EXISTS photo_owner;

CREATE TABLE photo_owner (
  user_id BIGINT NOT NULL,
  photo_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (photo_id) REFERENCES photo(id)
);


DROP TABLE IF EXISTS hashtag;

CREATE TABLE hashtag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS hashtag_photo;

CREATE TABLE hashtag_photo (
  photo_id BIGINT,
  hashtag_id BIGINT,
  PRIMARY KEY (photo_id, hashtag_id),
  FOREIGN KEY (photo_id) REFERENCES photo(id),
  FOREIGN KEY (hashtag_id) REFERENCES hashtag(id)
);

DROP TABLE IF EXISTS audit;

CREATE TABLE audit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(9),
  action VARCHAR(20) NOT NULL,
  subject VARCHAR(50) NOT NULL,
  object VARCHAR(255) NULL,
  PRIMARY KEY (id)
);
